### ISSUE TITLE
CI/CD Pipeline using git

### ISSUE THREAD

**Issue by floradu88** [jonathanevans/brown-bag#2]
Continuous integration Continous Delivery Pipeline using git

Quick demo of a working pipeline of a couple projects I am currently developing.

Tools used: Teamcity, git, powershell, devenv publish and git feature branching, dbup
Languages: c#, database project, javascript, typescript

**Comment by jonathanevans** [comment]
This talk is booked for the 27th February.

**Comment by jonathanevans** [comment]
Thank you Radu.

The video for this is now available on our training sharepoint site.
